language: go

go:
- 1.x
- "1.10"
- 1.14.x
- master

notifications:
  slack: 
    rooms:
      - faustohome:R86pQ3z5xcI25gNrLIjxLpcO#latimer
    on_success: always # default: always
    on_failure: always # default: always

script: go test -v ./...
